export const BRAND_PRIMARY_COLOR = "#004161";
export const BRAND_SECONDARY_COLOR = "#99CC33";
export const BRAND_PRIMARY_SHADE = "#0b5b85";
export const BRAND_SECONDARY_SHADE = "#7fb129";
export const BRAND_PRIMARY_TINT = "#2e6f8f";
export const BRAND_SECONDARY_TINT = "#bfdc7f";
export const BRAND_PRIMARY_DARK = "#1f5573";
export const BRAND_SECONDARY_DARK = "#6ca020";

export const BRAND_CHART_COLORS = [
  BRAND_PRIMARY_COLOR,
  BRAND_SECONDARY_COLOR,
  BRAND_PRIMARY_SHADE,
  BRAND_SECONDARY_SHADE,
  BRAND_PRIMARY_TINT,
  BRAND_SECONDARY_TINT,
  BRAND_PRIMARY_DARK,
  BRAND_SECONDARY_DARK,
] as const;
